name: Lint i18n
description: Lint i18n JSON key structure (naming conventions, nesting depth, missing keys across locales)

inputs:
  path:
    description: Path to the i18n directory containing locale JSON files
    required: true
  rules:
    description: Optional JSON string of lint rules to apply
    required: false
    default: '{}'

outputs:
  total-files-analyzed:
    description: Number of locale files analyzed

runs:
  using: node20
  main: dist/index.js
